BeeNotepadeWeb/Models/ErrorViewModel.cs
using System;

namespace ASPNetDemo.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BeeNotepadeWeb/Models/FirebaseError.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BeeNotepadeWeb.Models
{
    public class FirebaseError
    {
        public Error error { get; set; }
    }
    public class Error
    {
        public int code { get; set; }
        public string message { get; set; }
        public List<Error> errors { get; set; }
    }
}

BeeNotepadeWeb/Models/LoginModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace BeeNotepadeWeb.Models
{
    public class LoginModel
    {
        [Required]
        [EmailAddress]
        public string Email { get; set; }

        [Required]
        public string Password { get; set; }

        [Required]
        public string TgID { get; set; }
    }
}

BeeNotepadeWeb/Controllers/PasekaController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using CoreLibrary;
using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Firebase.Auth;
using Microsoft.AspNetCore.Http;
using Newtonsoft.Json;
using BeeNotepadeWeb.Models;

namespace BeeNotepadeWeb.Controllers
{
    public class PasekaController : Controller
    {
        private string path = @"..\CoreLibrary\data\";

        // ссылка на объект - хранилище ульев
        BeehiveStorage beehiveStorage;
        FirebaseAuthProvider auth;

        public PasekaController(IWebHostEnvironment _environment, IBeehiveStorage _beehiveStorage)
        {
            beehiveStorage = (BeehiveStorage)_beehiveStorage;
            auth = new FirebaseAuthProvider(
                            new FirebaseConfig("AIzaSyB9UEZ2WNg_Y2eKYTA-Q21OVNQx37HgqRw"));
        }
        public IActionResult Index()
        {
            var token = HttpContext.Session.GetString("_UserToken");
            

            if (token != null)
            {
                var user = HttpContext.Session.GetString("_UserEmail");
                var tgID = HttpContext.Session.GetString("_TgID");
                beehiveStorage.ReadFromFile($"{path}{user}-{tgID}.txt");
                var today = DateTime.Today;
                foreach (Beehive beehive in beehiveStorage.BeeGarden)
                {
                    beehive.DaysForCheck -= (int)Math.Round((today - beehive.AddDate).TotalDays);
                    beehive.AddDate = today;
                    if (beehive.DaysForCheck < 0)
                        beehive.DaysForCheck = 0;
                }
                var beeGarden = beehiveStorage.BeeGarden;
            
                return View(beeGarden);
            }
            else
            {
                return RedirectToAction("SignIn");
            }
        }

        public IActionResult Registration()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Registration(LoginModel loginModel)
        {
            try
            {
                //create the user
                await auth.CreateUserWithEmailAndPasswordAsync(loginModel.Email, loginModel.Password);
                //log in the new user
                var fbAuthLink = await auth
                                .SignInWithEmailAndPasswordAsync(loginModel.Email, loginModel.Password);
                string email = fbAuthLink.User.Email.Replace('.', '_').Replace('@', '_');
                string token = fbAuthLink.FirebaseToken;
                //saving the token in a session variable
                if (token != null)
                {
                    HttpContext.Session.SetString("_UserToken", token);
                    HttpContext.Session.SetString("_UserEmail", email);
                    HttpContext.Session.SetString("_TgID", loginModel.TgID);

                    return RedirectToAction("Index");
                }
            }
            catch (FirebaseAuthException ex)
            {
                var firebaseEx = JsonConvert.DeserializeObject<FirebaseError>(ex.ResponseData);
                ModelState.AddModelError(String.Empty, firebaseEx.error.message.Replace('_', ' '));
                return View(loginModel);
            }

            return View();

        }

        public IActionResult SignIn()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> SignIn(LoginModel loginModel)
        {
            try
            {
                //log in an existing user
                var fbAuthLink = await auth
                                .SignInWithEmailAndPasswordAsync(loginModel.Email, loginModel.Password);
                string token = fbAuthLink.FirebaseToken;
                string email = fbAuthLink.User.Email.Replace('.', '_').Replace('@', '_');
                var tgID = "";
                //save the token to a session variable
                if (token != null)
                {
                    var files = Directory.GetFiles(path);
                    foreach (var file in files)
                    {
                        Console.WriteLine(file);
                        if (file.Contains(email))
                        {
                            tgID = file.Split("-")[1].Replace(".txt", "");
                            break;
                        }

                    }
                    HttpContext.Session.SetString("_UserToken", token);
                    HttpContext.Session.SetString("_UserEmail", email);
                    HttpContext.Session.SetString("_TgID", tgID);

                    return RedirectToAction("Index");
                }

            }
            catch (FirebaseAuthException ex)
            {
                var firebaseEx = JsonConvert.DeserializeObject<FirebaseError>(ex.ResponseData);
                ModelState.AddModelError(String.Empty, firebaseEx.error.message.Replace('_', ' '));
                return View(loginModel);
            }

            return View();
        }

        public IActionResult LogOut()
        {
            HttpContext.Session.Remove("_UserToken");
            HttpContext.Session.Remove("_UserEmail");
            HttpContext.Session.Remove("_TgID");
            return RedirectToAction("SignIn");
        }

        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(Beehive beehive)
        {
            var user = HttpContext.Session.GetString("_UserEmail");
            var tgID = HttpContext.Session.GetString("_TgID");
            beehiveStorage.Add(beehive);
            beehiveStorage.WriteInFile($"{path}{user}-{tgID}.txt");
            return RedirectToAction("Index");
        }

        public IActionResult ChoiceBeehive()
        {

            return View(beehiveStorage.BeeGarden);
        }
        
        
        public IActionResult AddOffshoot(string id)
        {
            var user = HttpContext.Session.GetString("_UserEmail");
            var tgID = HttpContext.Session.GetString("_TgID");
            beehiveStorage.ChoiceBeehive(id);
            beehiveStorage.WriteInFile($"{path}{user}-{tgID}.txt");
            return View();
        }
        [HttpPost]
        public IActionResult AddOffshoot(Beehive beehive)
        {
            var user = HttpContext.Session.GetString("_UserEmail");
            var tgID = HttpContext.Session.GetString("_TgID");
            beehiveStorage.AddOffshoot(beehive);
            beehiveStorage.WriteInFile($"{path}{user}-{tgID}.txt");
            return RedirectToAction("Index");
        }

        public IActionResult Change(string id)
        {
            return View(beehiveStorage.FindById(id));
        }

        [HttpPost]
        public IActionResult Change(Beehive beehive)
        {
            var user = HttpContext.Session.GetString("_UserEmail");
            var tgID = HttpContext.Session.GetString("_TgID");
            beehiveStorage.Change(beehive);
            beehiveStorage.WriteInFile($"{path}{user}-{tgID}.txt");
            return RedirectToAction("Index");
        }
        public IActionResult Remove(string id)
        {
            var user = HttpContext.Session.GetString("_UserEmail");
            var tgID = HttpContext.Session.GetString("_TgID");
            beehiveStorage.RemoveById(id);
            beehiveStorage.WriteInFile($"{path}{user}-{tgID}.txt");
            return RedirectToAction("Index");
        }
    }
}

BeeNotepadeWeb/Views/Paseka/Add.cshtml
@model CoreLibrary.Beehive

<div class="row justify-content-lg-cehter">
    <h1>Добавление нового улья</h1>
</div>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Add">
            <div class="form-group">
                <label asp-for="Name" class="control-label">Название</label>
                <input asp-for="Name" class=" form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label">Описание</label>
                <input asp-for="Description" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label">Картинка</label>
                <input asp-for="Image" type="file" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="FiledFrames" class="control-label">Заполненных рамок</label>
                <input type="number" asp-for="FiledFrames" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Добавить" class=" btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Вернуться к пасеке</a>
</div>

BeeNotepadeWeb/Views/Paseka/AddOffshoot.cshtml
@model CoreLibrary.Beehive

<div class="row justify-content-lg-cehter">
    <h1>Добавление отводка</h1>
</div>

<div class="row">
    <div class="col-md-4">
        <form asp-action="AddOffshoot">
            <div class="form-group">
                <label asp-for="Name" class="control-label">Название</label>
                <input asp-for="Name" class=" form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label">Описание</label>
                <input asp-for="Description" value="Отводок." class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label">Картинка</label>
                <input asp-for="Image" type="file" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="FiledFrames" class="control-label">Заполненных рамок</label>
                <input type="number" asp-for="FiledFrames" value="6" class="form-control" />
            </div>
            <div class="form-group">
                <input type="checkbox" style="display: none" asp-for="IsLayering" checked="checked" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Добавить" class=" btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Вернуться к пасеке</a>
</div>

BeeNotepadeWeb/Views/Paseka/Change.cshtml
@using CoreLibrary
@model Beehive

<div class="row justify-content-lg-cehter">
    <h1>Изменить информацию</h1>
</div>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Change">
            <div class="form-group">
                <label asp-for="Id" class="control-label">Id улья: @Model.Id</label>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label">Название</label>
                <input asp-for="Name" value="@Model.Name" class=" form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label">Описание</label>
                <input asp-for="Description" value="@Model.Description" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label">Картинка</label>
                <input asp-for="Image" value="@Model.Image" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="FiledFrames" class="control-label">Заполненных рамок</label>
                <input type="number" asp-for="FiledFrames" value="@Model.FiledFrames" class="form-control" />
            </div>
            @if (Model.DaysForCheck > 0)
            {
                <label>Проверьте этот улей позже</label>
            }
            else
            {
                if (Model.IsLayering && (!Model.CheckQuinCells || !Model.IsCull))
                {
                    @if (!Model.CheckQuinCells)
                    {
                        <div class="form-group">
                            <label asp-for="CheckQuinCells" class="control-label">Проверил маточники</label>
                            <input type="checkbox" asp-for="CheckQuinCells" class="form-control" />
                        </div>
                    }
                    else
                    {
                        <input type="checkbox" style="display: none" asp-for="CheckQuinCells" checked="checked" class="form-control" />
                    }
                

                    @if (Model.CheckQuinCells)
                    {
                        <div class="form-group">
                            <label asp-for="IsCull" class="control-label">Сделал выбраковку</label>
                            <input type="checkbox" asp-for="IsCull" class="form-control" />
                        </div>
                    }
                
                }
                else 
                {
                    <input type="checkbox" style="display: none" asp-for="CheckQuinCells" checked="checked" class="form-control" />
                    <input type="checkbox" style="display: none" asp-for="IsCull" checked="checked" class="form-control" />

                    <div class="form-group">
                        <label asp-for="CheckBeehive" class="control-label">Проверил улей</label>
                        <input type="checkbox" asp-for="CheckBeehive" class="form-control" />
                    </div>
                    
                }
                <div class="form-group">
                    <input type="submit" value="Сохранить" class=" btn btn-primary" />
                </div>
            }
            


            
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Вернуться к пасеке</a>
</div>

BeeNotepadeWeb/Views/Paseka/ChoiceBeehive.cshtml
@using CoreLibrary;
@model List<Beehive>

<h2>Создание отводков</h2>

<br>

<div class="row">
    @foreach (var beehive in Model)
    {
        if (beehive.FiledFrames >= 12)
        {
            <div class="col-md-4 mb-5">
                <div class="card text-center h-100">
                    <div class="card-header bg-transparent border-0">
                        <h2 class="card-title text-center">
                            <a>@beehive.Name</a>
                        </h2>
                        <p class="font-weight-normal">@beehive.Description</p>
                    </div>
                    <div class="card-body">
                        <img class="card-img-top" src="../../@beehive.Image"/>
                        
                    </div>
                    <div class="card-footer">
                        <a class="btn btn-primary" asp-controller="Paseka"
                           asp-action="AddOffshoot" asp-route-id="@beehive.Id"
                           role="button">
                            Выбрать
                        </a>

                    </div>
                </div>
            </div> 
        }
    }
</div>

<div>
    <a asp-action="Index">Вернуться к пасеке</a>
</div>

BeeNotepadeWeb/Views/Paseka/Index.cshtml
@using CoreLibrary;
@model List<Beehive>

<h2>Пасека</h2>
<div class="row justify-content-end">
    <a class="btn btn-primary mr-1" asp-controller="Paseka"
       asp-action="Add" role="button">Добавить улей</a>
    <a class="btn btn-primary mr-1" asp-controller="Paseka"
       asp-action="ChoiceBeehive" role="button">Создать отводок</a>
    <a class="btn btn-danger" asp-controller="Paseka"
       asp-action="LogOut" role="button">Выйти</a>
</div>
<br>

<div class="row">
    @foreach (var beehive in Model)
    {
        <div class="col-md-4 mb-5">
            <div class="card text-center h-100">
                <div class="card-header bg-transparent border-0">
                    <h2 class="card-title text-center">
                        <a>@beehive.Name</a>
                    </h2>
                    <p class="font-weight-normal">@beehive.Description</p>
                </div>
                <div class="card-body">
                    <img class="card-img-top" src="@beehive.Image"/>
                </div>
                <div class="card-footer">
                    <p class="font-weight-normal">Дней до проверки @beehive.DaysForCheck</p>
                    <a class="btn btn-danger" asp-controller="Paseka"
                       asp-action="Remove" asp-route-id="@beehive.Id"
                       role="button">
                        Удалить
                    </a>
                    <a class="btn btn-primary" asp-controller="Paseka"
                       asp-action="Change" asp-route-id="@beehive.Id"
                       role="button">
                        Изменить
                    </a>
                </div>
            </div>
        </div>
    }
</div>

BeeNotepadeWeb/Views/Paseka/Registration.cshtml
@model BeeNotepadeWeb.Models.LoginModel

@{
    ViewData["Title"] = "Registration";
}

<h1>Регистрация</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Registration">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" type="password" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TgID" class="control-label">Telegram ID</label>
                <input asp-for="TgID" class="form-control" />
            </div>
            <div class="form-group">
                <label class="control-label">Для получения Telegram ID перейдите сюда </label>
                <a href="https://t.me/getmyid_bot">@@getmyid_bot</a>
            </div>
            <div class="form-group">
                <input type="submit" value="Отправить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="SignIn">Уже есть аккаунт? Войти</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BeeNotepadeWeb/Views/Paseka/SignIn.cshtml
@model BeeNotepadeWeb.Models.LoginModel

@{
    ViewData["Title"] = "SignIn";
}

<h1>Авторизация</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="SignIn">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" type="password" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Войти" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Registration">Регистрация</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BeeNotepadeWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BeeNotepade</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">BeeNotepade</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Paseka" asp-action="Index">Пасека</a>
                        </li>
                        
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - BeeNotepade
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>